### ISSUE TITLE
zmodload zdharma/zplugin

### ISSUE THREAD

**Issue by jrc2139** [zdharma-continuum/zinit-configs#3]
https://github.com/zdharma-continuum/zinit-configs/blob/d63f1934bc0a7fb81d7a71db9e8fa660b1309812/NICHOLAS85/.zshrc#L44

was zdharma/zplugin the same as this project https://github.com/xPMo/zplugin ?

**Comment by vladdoster** [comment]
@jrc2139 Not sure what your question is? Look at the commit history or releases and it should answer your question.
